### ISSUE TITLE
Bug: Able to edit text of the Bible

### ISSUE THREAD

**Issue by Sheumais** [Bible-Projects/believers-sword-app#59]
**Describe the bug**
Ability to edit the text of the Bible.

**To Reproduce**
1. Go to the 'Read Bible' tab
2. Pick any two Bible translations on the right side
3. Double click the text of a verse which is the _most recently selected translation_
4. Delete/Edit the text

**Expected behavior**
Bible should not be able to be edited.

**Screenshots**
![image](https://user-images.githubusercontent.com/88064574/165468923-f7d54cb3-e6c6-4fc2-8382-4c3913a1f246.png)

**Desktop:**
 - OS: Windows 10
 - Version 0.8.2

**Comment by BroJenuel** [comment]
thanks for pointing this out,,, thanks a lot mate,,, :)

**Comment by BroJenuel** [comment]
new Update was made with this fix. :) God is Good all the time.
